# Generated by Django 4.2.2 on 2023-06-17 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deposits',
            new_name='Deposit',
        ),
        migrations.RenameModel(
            old_name='Withdrawals',
            new_name='Withdrawal',
        ),
    ]
